MPEPromo/Pages/Questionnaire/Export.cshtml.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.IO;
using System.Linq;
using System.Net.Mail;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using MPEPromo.Model;

namespace MPEPromo.Pages.Questionnaire
{
    public class ExportModel : PageModel
    {
        [BindProperty]
        [DisplayName("Enter Wave to Export: ")]
        [Required(ErrorMessage = "Wave Number is required.")]
        [MinLength(4)]
        public string waveInput { get; set; }

        private ApplicationDbContext _db;

        public ExportModel(ApplicationDbContext db)
        {
            _db = db;
        }

        public IEnumerable<MPEPromoModel> MPEPromo_Records { get; set; }

        public void OnGet()
        {

        }

        public IActionResult OnPostExport(string waveInput)
        {
            if (waveInput == null)
            {
                ModelState.AddModelError("waveInput", "Wave Number is required.");
                return Page();
            }

            if (!ModelState.IsValid)
            {
                return Page();
            }

            if (waveInput != null)
            {
                MPEPromo_Records = _db.MPEPromo_Data.Where(x => x.Wave == waveInput);

                string FileName = "MPEPromo_Data" + waveInput + ".txt";

                //Write Data to File

                //StreamWriter file = new StreamWriter(@"\\CAP12DC01\Shared\MPEPromo\MPEPromo_Data" + waveInput + ".txt");
                StreamWriter file = new StreamWriter(@"\\CAP12DC01\Shared\MPEPromo\" + FileName);

                foreach (MPEPromoModel line in MPEPromo_Records)
                {


                    file.WriteLine(
                        "{0}\t{1}\t{2}\t{3}\t{4}\t{5}\t{6}\t{7}\t{8}\t{9}\t{10}",
                        line.StoreNum,
                        line.Wave,
                        line.ItemID,
                        line.Brand_ID,
                        line.Location,
                        line.Pack_Disc,
                        line.Carton_Disc,
                        line.Pack_Sell,
                        line.Carton_Sell,
                        line.NumSigns,
                        Convert.ToInt16(line.Tax)
 
                        );
                }

                file.Close();

                SendMail(FileName);

                return RedirectToPage("/Index");
            }

            return Page();


        }

        private void SendMail(string FileName)
        {
            try
            {
                MailMessage mailMessage = new MailMessage();
                mailMessage.To.Add("mhalatin@capstoneresearch.com");
                //mailMessage.To.Add("dpriff@capstoneresearch.com");
                //mailMessage.To.Add("tsperger@capstoneresearch.com");
                mailMessage.From = new MailAddress("mhalatin@capstoneresearch.com");
                mailMessage.Subject = "MPEPromo Data Export e-mail";
                mailMessage.Body = "s:/MPEPromo/" + FileName + " Exported!";
                SmtpClient smtpClient = new SmtpClient("CAP12EXCH01.CAPSTONE.local");
                smtpClient.Send(mailMessage);
                Console.Write("Data Exported!");

            }
            catch (Exception ex)
            {
                Console.Write("Could not export data - error: " + ex.Message);

            }
        }
    }
}

MPEPromo/Pages/Questionnaire/GetStore.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using MPEPromo.Model;
using Dapper;

namespace MPEPromo.Pages.Questionnaire
{
    public class GetStoreModel : PageModel
    {
        private ApplicationDbContext _db;
        public GetStoreModel(ApplicationDbContext db)
        {
            _db = db;
        }


        [BindProperty]
        public MPEPromoModel MPEPromo_Data { get; set; }

        [BindProperty]
        public IList<MPEPromoModel> Sign_Array { get; set; } = new MPEPromoModel[20].ToList();

        [BindProperty]
        public IEnumerable<MPEPromoModel> MPEPromo_Records { get; set; }
        public IList<MPEPromoModel> Sign_Array2 { get; set; }


        public async Task OnGet(string storeInput, string waveInput)
        {
            MPEPromo_Records = await _db.MPEPromo_Data.ToListAsync();
            MPEPromo_Records = _db.MPEPromo_Data.Where(x => x.StoreNum == storeInput && x.Wave == waveInput).OrderBy(x => x.ItemID);

            Sign_Array2 = MPEPromo_Records.ToList();


            for ( int i = 0; i < Sign_Array2.Count(); i++)
            {
                if ( Sign_Array2[i].ItemID == "101")
                {
                    Sign_Array[0] = Sign_Array2[i];
                }
                if (Sign_Array2[i].ItemID == "102")
                {
                    Sign_Array[1] = Sign_Array2[i];
                }
                if (Sign_Array2[i].ItemID == "103")
                {
                    Sign_Array[2] = Sign_Array2[i];
                }
                if (Sign_Array2[i].ItemID == "104")
                {
                    Sign_Array[3] = Sign_Array2[i];
                }
                if (Sign_Array2[i].ItemID == "105")
                {
                    Sign_Array[4] = Sign_Array2[i];
                }
                if (Sign_Array2[i].ItemID == "106")
                {
                    Sign_Array[5] = Sign_Array2[i];
                }
                if (Sign_Array2[i].ItemID == "107")
                {
                    Sign_Array[6] = Sign_Array2[i];
                }
                if (Sign_Array2[i].ItemID == "108")
                {
                    Sign_Array[7] = Sign_Array2[i];
                }
                if (Sign_Array2[i].ItemID == "109")
                {
                    Sign_Array[8] = Sign_Array2[i];
                }
                if (Sign_Array2[i].ItemID == "110")
                {
                    Sign_Array[9] = Sign_Array2[i];
                }
                if (Sign_Array2[i].ItemID == "111")
                {
                    Sign_Array[10] = Sign_Array2[i];
                }

                if (Sign_Array2[i].ItemID == "320")
                {
                    Sign_Array[11] = Sign_Array2[i];
                }
                if (Sign_Array2[i].ItemID == "510")
                {
                    Sign_Array[12] = Sign_Array2[i];
                }
                if (Sign_Array2[i].ItemID == "430")
                {
                    Sign_Array[13] = Sign_Array2[i];
                }
                if (Sign_Array2[i].ItemID == "43A")
                {
                    Sign_Array[14] = Sign_Array2[i];
                }

            }
        }


        public async Task<IActionResult> OnPost()
        {

            if (Sign_Array[0].StoreNum == null || Sign_Array[0].StoreNum.Length != 6)
            {
                ModelState.AddModelError(string.Empty, "Invalid Store Number");
            }
            if (Sign_Array[0].Wave == null || Sign_Array[0].Wave.Length != 4)
            {
                ModelState.AddModelError(string.Empty, "Invalid Wave Number");
            }

            MPEPromo_Data.StoreNum = Sign_Array[0].StoreNum;
            MPEPromo_Data.Wave = Sign_Array[0].Wave;


            if (!ModelState.IsValid)
            {
                return Page();
            }

            bool hasInfo = false;

            for (int i = 0; i <= 14; i++) //14
            {

                //Skip if nothing on line
                if (
                    (Sign_Array[i].Brand_ID == "0" || Sign_Array[i].Brand_ID == null) &&
                    (Sign_Array[i].Location == "0" || Sign_Array[i].Location == null) &&
                    Sign_Array[i].Pack_Disc == null &&
                    Sign_Array[i].Carton_Disc == null &&
                    Sign_Array[i].Pack_Sell == null &&
                    Sign_Array[i].Pack_Disc == null &&
                    Sign_Array[i].NumSigns == null
                    )
                { continue; }

                hasInfo = true;

                MPEPromo_Data.ItemID = GetItemCode(i);

                //Errors
                if (i >= 0 && i <= 10)
                {
                    if (Sign_Array[i].Brand_ID == "0")
                    {
                        ModelState.AddModelError(string.Empty, "Must have Brand ID on Sign for " + MPEPromo_Data.ItemID);
                    }
                    if (Sign_Array[i].Location == "0")
                    {
                        ModelState.AddModelError(string.Empty, "Must have Location of Sign for " + MPEPromo_Data.ItemID);
                    }
                }
                if ((i >= 0 && i <= 10) || i == 14)
                {
                    if (Sign_Array[i].Pack_Disc == null && Sign_Array[i].Carton_Disc == null)
                    {
                        ModelState.AddModelError(string.Empty, "Must have a Discount Price for " + MPEPromo_Data.ItemID);
                    }
                }
                if ((i >= 0 && i <= 10) || i == 14)
                {
                    if (Sign_Array[i].Pack_Sell == null && Sign_Array[i].Carton_Sell == null)
                    {
                        ModelState.AddModelError(string.Empty, "Must have a Selling Price for " + MPEPromo_Data.ItemID);
                    }
                }
                if (i >= 0 && i <= 10)
                {
                    if (Sign_Array[i].NumSigns == null)
                    {
                        ModelState.AddModelError(string.Empty, "Must have Number of Sign for " + MPEPromo_Data.ItemID);
                    }
                }

                if (!ModelState.IsValid)
                {
                    return Page();
                }
            }

            if (hasInfo == false)
            {

                ModelState.AddModelError(string.Empty, "No INFO !!");

                if (!ModelState.IsValid)
                {
                    return Page();
                }

            }

            _db.MPEPromo_Data.RemoveRange(_db.MPEPromo_Data.Where(x => x.StoreNum == Sign_Array[0].StoreNum && x.Wave == Sign_Array[0].Wave));
            await _db.SaveChangesAsync();

            for (int i = 0; i <= 14; i++) //14
            {

                //Skip if nothing on line
                if (
                    (Sign_Array[i].Brand_ID == "0" || Sign_Array[i].Brand_ID == null) &&
                    (Sign_Array[i].Location == "0" || Sign_Array[i].Location == null) &&
                    Sign_Array[i].Pack_Disc == null &&
                    Sign_Array[i].Carton_Disc == null &&
                    Sign_Array[i].Pack_Sell == null &&
                    Sign_Array[i].Pack_Disc == null &&
                    Sign_Array[i].NumSigns == null
                    )
                { continue; }

                MPEPromo_Data.ItemID = GetItemCode(i);

                MPEPromo_Data.Brand_ID = Sign_Array[i].Brand_ID;
                MPEPromo_Data.Location = Sign_Array[i].Location;
                MPEPromo_Data.Pack_Disc = Sign_Array[i].Pack_Disc;
                MPEPromo_Data.Carton_Disc = Sign_Array[i].Carton_Disc;
                MPEPromo_Data.Pack_Sell = Sign_Array[i].Pack_Sell;
                MPEPromo_Data.Carton_Sell = Sign_Array[i].Carton_Sell;
                MPEPromo_Data.NumSigns = Sign_Array[i].NumSigns;
                MPEPromo_Data.Tax = Sign_Array[i].Tax;

                MPEPromo_Data.UpdateDT = DateTime.Now;

                //generate unique key id field in database without IDENTITY(1,1)
                Guid g;
                g = Guid.NewGuid();
                MPEPromo_Data.ID = g;

                _db.MPEPromo_Data.Add(MPEPromo_Data);

                await _db.SaveChangesAsync();

            }

            return RedirectToPage("/Index");
        }

        public async Task<IActionResult> OnPostDelete()
        {
            _db.MPEPromo_Data.RemoveRange(_db.MPEPromo_Data.Where(x => x.StoreNum == Sign_Array[0].StoreNum && x.Wave == Sign_Array[0].Wave));
            await _db.SaveChangesAsync();

            return RedirectToPage("/Index");
        }

        //subs
        private string GetItemCode(int i)
        {
            string code;

            if (i == 11) code = "320";
            else if (i == 12) code = "510";
            else if (i == 13) code = "430";
            else if (i == 14) code = "43A";
            else code = (i + 101).ToString();

            return code;
        }


    }
}

MPEPromo/Pages/Questionnaire/Search.cshtml.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using MPEPromo.Model;

namespace MPEPromo.Pages.Questionnaire
{
    public class SearchModel : PageModel
    {
        [DisplayName("Store Number: ")]
        public string storeInput { get; set; }
        [DisplayName("Wave: ")]
        public string waveInput { get; set; }

        private ApplicationDbContext _db;

        public SearchModel(ApplicationDbContext db)
        {
            _db = db;
        }

        [BindProperty]
        public MPEPromoModel MPEPromo_Data { get; set; }
        public IEnumerable<MPEPromoModel> MPEPromo_Records { get; set; }

        public async Task OnGet()
        {
            MPEPromo_Records = await _db.MPEPromo_Data.ToListAsync();
            MPEPromo_Records = MPEPromo_Records.GroupBy(x => new { x.StoreNum,x.Wave }).Select(x => x.FirstOrDefault());
            MPEPromo_Records = MPEPromo_Records.OrderByDescending(x => x.Wave).ThenBy(x => x.StoreNum);
        }

        public async Task<IActionResult> OnPostSearch(string storeInput, string waveInput)
        {

            if ((storeInput != null) && (waveInput != null))
            {
                MPEPromo_Records = _db.MPEPromo_Data.Where(x => x.StoreNum == storeInput && x.Wave == waveInput);
            }
            else if (storeInput != null)
            {
                MPEPromo_Records = _db.MPEPromo_Data.Where(x => x.StoreNum == storeInput);
            }
            else if (waveInput != null)
            {
                MPEPromo_Records = _db.MPEPromo_Data.Where(x => x.Wave == waveInput);
            }
            else
            {
                MPEPromo_Records = await _db.MPEPromo_Data.ToListAsync();
            }

            MPEPromo_Records = MPEPromo_Records.OrderByDescending(x => x.Wave).ThenBy(x => x.StoreNum);

            return Page();

        }
    }
}

MPEPromo/Pages/Questionnaire/Export.cshtml
@page
@model MPEPromo.Pages.Questionnaire.ExportModel
@{

}

<br />
<h2>Export</h2>
<br />

<div style="border:1px solid #bbb9b9; border-radius:5px;">
    <form method="post">


        <br />

        <div class="row" style="padding-left:50px; padding-top:30px;">
            <div class="form-group">
                <div class="row">

                    <div class="col-sm-5">
                        <label asp-for="@Model.waveInput"></label>
                    </div>
                    <div class="col-sm-3">
                        <input asp-for="@Model.waveInput" maxlength="4" class="form-control" />
                        <span asp-validation-for="@Model.waveInput" class="text-danger"></span>
                    </div>

                </div>
                <br />
                <div class="row">

                    <div class="col-sm-12">
                        <b>File will be exported to: s:/MPEPromo as MPEPromo_Data"wave".txt</b>
                    </div>

                </div>
            </div>
        </div>

        <br />
        <div class="row" style="padding-left:50px; padding-top:30px;">
            <div class="form-group">

                    <button asp-page-handler="Export" class="btn btn-md btn-danger">Export Data</button>


                    <a asp-page="/Index" class="btn btn-success btn-md">Cancel</a>


            </div>
        </div>
        <br />
    </form>
</div>

MPEPromo/Pages/Questionnaire/GetStore.cshtml
@page
@model MPEPromo.Pages.Questionnaire.GetStoreModel
@{

}

<div>
    <form method="post">

        <div class="row" style="padding-left:50px; padding-top:30px;">
            <div class="form-group">
                <div class="row">

                    <div class="col-sm-3">
                        <label>Store Number: </label>
                    </div>
                    <div class="col-sm-3">
                        <input asp-for="Sign_Array[0].StoreNum" maxlength="6" class="form-control" style="border:none;border-bottom:2px solid" readonly />
                    </div>

                    <div class="col-sm-2">
                        <label>Wave: </label>
                    </div>
                    <div class="col-sm-3">
                        <input asp-for="Sign_Array[0].Wave" maxlength="4" class="form-control" style="border:none;border-bottom:2px solid" readonly />
                    </div>

                </div>
            </div>
        </div>

        <div asp-validation-summary="All" class="text-danger">
        </div>

        <table class="table table-bordered table-hover border-collapse:collapse" style="border:double">

            <thead>
                <tr>
                    <th colspan="1"></th>
                    <th colspan="4" style="text-align:center;border-left:double">Brand Id on Sign</th>
                    <th colspan="8" style="text-align:center;border-left:double">Location of Sign</th>
                    <th colspan="4" style="text-align:center;border-left:double;border-right:double">Sign Message</th>
                </tr>
                <tr>
                    <th></th>
                    <th style="border-left:double">None</th>
                    <th>Newport</th>
                    <th>Camel</th>
                    <th>Both</th>

                    <th style="border-left:double">None</th>
                    <th>Outdoor at Gas Pump</th>
                    <th>Window/Door Outside</th>
                    <th>Outdoor Other</th>
                    <th>Indoor Merch Rack</th>
                    <th>Indoor Ceiling</th>
                    <th>Window/Door Inside</th>
                    <th>Indoor Other</th>

                    <th style="width:20px;border-left:double">Pack Discount Amount</th>
                    <th>Carton Discount Amount</th>

                    <th>Pack Selling Amount</th>
                    <th>Carton Selling Amount</th>

                    <th style="border-left:double;border-top:double"># Signs at Store Today</th>
                </tr>
            </thead>
            <tbody>
                @for (var j = 101; j <= 111; j++)
                {
                    <tr>
                        <th scope="row">@j</th>

                        <td style="border-left:double;background-color:lightgray"><input asp-for="Sign_Array[j - 101].Brand_ID" type="radio" id="ID[@j]" value="0" checked /></td>
                        <td><input asp-for="Sign_Array[j - 101].Brand_ID" type="radio" id="ID[@j]" value="1" /></td>
                        <td><input asp-for="Sign_Array[j - 101].Brand_ID" type="radio" id="ID[@j]" value="2" /></td>
                        <td><input asp-for="Sign_Array[j - 101].Brand_ID" type="radio" id="ID[@j]" value="3" /></td>

                        <td style="border-left:double;background-color:lightgrey"><input asp-for="Sign_Array[j - 101].Location" type="radio" id="LOC[@j]" value="0" checked /></td>
                        <td><input asp-for="Sign_Array[j - 101].Location" type="radio" id="LOC[@j]" value="1" /></td>
                        <td><input asp-for="Sign_Array[j - 101].Location" type="radio" id="LOC[@j]" value="2" /></td>
                        <td><input asp-for="Sign_Array[j - 101].Location" type="radio" id="LOC[@j]" value="3" /></td>
                        <td><input asp-for="Sign_Array[j - 101].Location" type="radio" id="LOC[@j]" value="4" /></td>
                        <td><input asp-for="Sign_Array[j - 101].Location" type="radio" id="LOC[@j]" value="5" /></td>
                        <td><input asp-for="Sign_Array[j - 101].Location" type="radio" id="LOC[@j]" value="6" /></td>
                        <td><input asp-for="Sign_Array[j - 101].Location" type="radio" id="LOC[@j]" value="7" /></td>

                        <td style="border-left:double"><input asp-for="Sign_Array[j - 101].Pack_Disc" type="text" id="PRICE[@j]" style="width:80px" placeholder="0" /></td>
                        <td><input asp-for="Sign_Array[j - 101].Carton_Disc" type="text" id="PRICE[@j]" style="width:80px" placeholder="0" /></td>
                        <td><input asp-for="Sign_Array[j - 101].Pack_Sell" type="text" id="PRICE[@j]" style="width:80px" placeholder="0" /></td>
                        <td><input asp-for="Sign_Array[j - 101].Carton_Sell" type="text" id="PRICE[@j]" style="width:80px" placeholder="0" /></td>
                        <td style="border-left:double"><input asp-for="Sign_Array[j - 101].NumSigns" type="text" id="PRICE[@j]" style="width:80px" placeholder="0" /></td>

                    </tr>
                }

            </tbody>

        </table>

        <table class="table table-bordered table-hover" style="border:double">

            <thead>
                <tr>
                    <th style="width:80px">Description</th>
                    <th style="width:80px">Pack Selling Price</th>
                    <th style="width:80px">Tax Inluded</th>
                </tr>

            </thead>
            <tbody>
                <tr>
                    <th scope="row">Newport Menthol Box (320)</th>
                    <td><input asp-for="Sign_Array[11].Pack_Sell" type="text" style="width:80px" placeholder="0" /></td>
                    <td><input asp-for="Sign_Array[11].Tax" type="checkbox" /></td>
                </tr>
                <tr>
                    <th scope="row">Camel Blue Box (510)</th>
                    <td><input asp-for="Sign_Array[12].Pack_Sell" type="text" style="width:80px" placeholder="0" /></td>
                    <td><input asp-for="Sign_Array[12].Tax" type="checkbox" /></td>
                </tr>
                <tr>
                    <th scope="row">Marlboro Red Box (430)</th>
                    <td><input asp-for="Sign_Array[13].Pack_Sell" type="text" style="width:80px" placeholder="0" /></td>
                    <td><input asp-for="Sign_Array[13].Tax" type="checkbox" /></td>
                </tr>

            </tbody>

        </table>




        <table class="table table-bordered table-hover" style="border:double">

            <thead>

                <tr>
                    <th colspan="3"></th>
                    <th colspan="4" style="text-align:center">Sign Message</th>
                </tr>
                <tr>
                    <th colspan="3"></th>

                    <th>Pack Discount Amount</th>
                    <th>Carton Discount Amount</th>

                    <th>Pack Selling Amount</th>
                    <th>Carton Selling Amount</th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <th scope="row" colspan="3">Marlboro 2Pk Promo Sign (43A)</th>
                    <td><input asp-for="Sign_Array[14].Pack_Disc" type="text" style="width:80px" placeholder="0" /></td>
                    <td><input asp-for="Sign_Array[14].Carton_Disc" type="text" style="width:80px" placeholder="0" /></td>
                    <td><input asp-for="Sign_Array[14].Pack_Sell" type="text" style="width:80px" placeholder="0" /></td>
                    <td><input asp-for="Sign_Array[14].Carton_Sell" type="text" style="width:80px" placeholder="0" /></td>
                </tr>


            </tbody>

        </table>


        <br />
        <div class="row" style="padding-left:50px; padding-top:30px;">
            <div class="form-group">
                <input type="submit" value="Update" class="btn btn-primary btn-md" />
                &nbsp;
                <a asp-page="/Index" class="btn btn-success btn-md">Cancel</a>
                &nbsp;
                &nbsp;
                &nbsp;
                &nbsp;
                &nbsp;
                <button asp-page-handler="Delete" class="btn btn-danger btn-md">Delete Entire Store</button>
            </div>
        </div>




    </form>
</div>

MPEPromo/Pages/Questionnaire/Search.cshtml
@page
@model MPEPromo.Pages.Questionnaire.SearchModel
@{
    ViewData["Title"] = "Search";
}

<br />
<h2>Search</h2>
<br />


<div style="border:1px solid #bbb9b9; border-radius:5px;">
    <form method="post">


        <br />

        <div class="row" style="padding-left:50px; padding-top:30px;">
            <div class="form-group">
                <div class="row">

                    <div class="col-sm-2">
                        <label asp-for="@Model.storeInput"></label>
                    </div>
                    <div class="col-sm-3">
                        <input asp-for="@Model.storeInput" maxlength="6" class="form-control" />
                        <span asp-validation-for="@Model.storeInput" class="text-danger"></span>
                    </div>

                    <div class="col-sm-1">
                        <label asp-for="@Model.waveInput"></label>
                    </div>
                    <div class="col-sm-3">
                        <input asp-for="@Model.waveInput" maxlength="4" class="form-control" />
                        <span asp-validation-for="@Model.waveInput" class="text-danger"></span>
                    </div>

                </div>
            </div>
        </div>
        <br />
        <div class="row" style="padding-left:50px; padding-top:30px;">
            <div class="form-group">
                <div class="row">
                    <div class="col-sm-6">
                        <button asp-page-handler="Search" class="btn btn-sm btn-primary">Search</button>
                    </div>
                    <div class="col-sm-6">
                        <a asp-page="/Index" class="btn btn-success btn-sm">Main Menu</a>
                    </div>
                    <div class="col-sm-12">
                    </div>
                </div>
            </div>
        </div>
        <br />
    </form>
</div>


@if (Model.MPEPromo_Records.Count() > 0)
{

    <form method="post">
        <div>
            <br />
            <table class="table table-condensed table-hover">
                <tr>
                    <th>
                        @Html.DisplayNameFor(m => m.MPEPromo_Records.FirstOrDefault().StoreNum) (@Model.MPEPromo_Records.Count())
                    </th>
                    <th>
                        @Html.DisplayNameFor(m => m.MPEPromo_Records.FirstOrDefault().Wave)
                    </th>
                    <th>
                    </th>
                </tr>
                @foreach (var item in Model.MPEPromo_Records)
                {
                    <tr>
                        <td>
                            @Html.DisplayFor(m => item.StoreNum)
                        </td>
                        <td>
                            @Html.DisplayFor(m => item.Wave)
                        </td>
                        <td>
                            <a asp-page="./GetStore" asp-route-storeInput="@item.StoreNum" asp-route-waveInput="@item.Wave" class="btn btn-sm btn-success">Get Store</a>
                        </td>
                    </tr>
                }
            </table>
        </div>
    </form>
}
else
{
    <p>No Questionnaires Found.</p>
}